@extends('layout.app')
@section('keywords', "privacy, information we keep, important user information, we steal your data, wd school")
@section('description', "School of web development school privacy policy")

@section('title', "School of Web Development")


@section('content')
<div class="container custom-border my-3">
    <div class="row  mx-5">
<p><h2>Privacy Policy</h2>
 This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.

 We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
 <br><br><hr><br>

 <h2>Definitions</h2>
For the purposes of this Privacy Policy:<br>

 <ul class="mb-4">
   <li><b>Account</b> means a unique account created for You to access our Service or parts of our Service.</li>
   <li><b>Country</b> refers to: Ontario, Canada</li>
   <li><b>Device</b> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
   <li><b>Personal Data</b> is any information that relates to an identified or identifiable individual.</li>
   <li><b>Service</b> refers to the Website.</li>
   <li><b>Service Provider</b> means any natural or legal person who processes the data on behalf of the University.</li>
   <li><b>Usage Data</b> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
   <li><b>Website</b> refers to University of Web Development, accessible from </li>
   <li><b>You </b>means the individual accessing or using the Service, or the University, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
 </ul>

 <br><br><hr><br>

 <h2>Collecting and Using Your Personal Data</h2><br>
 <h3>Types of Data Collected</h3><br>
 <br><br><hr><br>
 <h4>Personal Data</h4>
 While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:<br>
 <ul>
   <li>Email Address</li>
   <li>First name and Last name</li>
   <li>Phone number</li>
   <li>Address, State, Province, ZIP/Postal code, City</li>
   <li>Usage Data</li>
 </ul>
 <br><br><br><br>
 <h4>Usage Data</h4>
 Usage Data is collected automatically when using the Service.<br>
 Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
<br>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
<br>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.

<br><br><hr><br>

<h2>Security of Your Personal Data</h2><br>
 The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.

 <br><br><hr>


 <br><h2>Changes to this Privacy Policy</h2>
 We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
 <br>
 We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.

 <br><br><hr><br>

</div>
</div>
</p>

@endsection
